version: '3.7'

services:
    database: 
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
          - 5432:5432
        environment:
          - POSTGRES_USER=docker
          - POSTGRES_PASSWORD=ignite
          - POSTGRES_DB=rentx
        volumes:
          - pgdata:/data/postgres
  # app:
  #   build: .
  #   # command: npm run-script dev
  #   container_name: rentx
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/usr/app  

volumes:
  pgdata:
    driver: local